In [3]:
from libfmp.b import FloatingBox
import numpy as np
import os
import sys
import librosa
from scipy import signal
from matplotlib import pyplot as plt
import matplotlib.gridspec as gridspec
import IPython.display as ipd
import pandas as pd
from numba import jit

import libfmp.c6
import libfmp.c4
import libfmp.c3
import libfmp.c2
import libfmp.b

sys.path.append('..')

In [11]:
# Generate normalized feature sequence
K = 4
M = 100
r = np.arange(M)
b1 = np.zeros((K, M))
b1[0, :] = r
b1[1, :] = M-r
b2 = np.ones((K, M))

X = np.concatenate((b1, b1, np.roll(b1, 2, axis=0), b2, b1), axis=1)
 
Y = np.transpose(X)
 
#X = libfmp.c3.normalize_feature_sequence(X, norm='2', threshold=0.001)

[[  0.   1.   2. ...  97.  98.  99.]
 [100.  99.  98. ...   3.   2.   1.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]]
[[  0. 100.   0.   0.]
 [  1.  99.   0.   0.]
 [  2.  98.   0.   0.]
 ...
 [ 97.   3.   0.   0.]
 [ 98.   2.   0.   0.]
 [ 99.   1.   0.   0.]]


In [12]:
# Compute SSM
S = np.dot(Y, X)
print(S)

[[10000.  9900.  9800. ...   300.   200.   100.]
 [ 9900.  9802.  9704. ...   394.   296.   198.]
 [ 9800.  9704.  9608. ...   488.   392.   296.]
 ...
 [  300.   394.   488. ...  9418.  9512.  9606.]
 [  200.   296.   392. ...  9512.  9608.  9704.]
 [  100.   198.   296. ...  9606.  9704.  9802.]]
